# main:
# 	gcc -c main.c
# 	gcc -g main.o -o main

# main:
# 	gcc -c valdgrind.c 
# 	gcc -g valdgrind.o -o main


main:
	gcc -c sample2.c 
	gcc -g sample2.o -o main


clean:
	rm -f main *.o

.PHONY: clean